#!/usr/bin/env python

# -*- coding: utf-8 -*-

import sys, os

from optparse import OptionParser

Q = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.abspath(Q + "/../src"))

from dfs.version import Version
from dfs.config import Config

from dfs.cmd import Cmd

def main():
    # init help
    cmd = Cmd()
    cmds = "\r\nCommands:\r\n" + cmd.get_help()
    # parse arguments
    parser = OptionParser(usage="usage: %prog [cmd] [options]" + cmds, version="%prog " + Version.VERSION)
    # parser.add_option("-v", "--verbose", dest="verbose", action="store_true",
    #                   default="False", help="verbose output")
    # parser.add_option("-t", "--target", desc="target", action="", default="", help="target volume")
    parser.add_option("-f", "--force", dest="force", action="store_true",
        default=False, help="force operation")

    # parse arguments
    config = Config()
    config.set_parser(parser)
    opts = config.get_opts()
    if len(opts) <= 0:
        print "dfs: no command given (try -h)"
        sys.exit(-1)
    cmd.set_opt(opts[0])
    cmd.validate()
    if cmd.invalid_cmd():
        print "dfs: %s: invalid command" % opts[0]
        sys.exit(-1)
    if cmd.has_errors():
        print "dfs: " + cmd.get_errors_str()
        sys.exit(-1)
    cmd.run()

# entry point
if __name__ == "__main__":
    main()
